### PR TITLE
Added UI for the login

### PR DESCRIPTION
**Pull request by jimoskar**
Implemented a UI for the login. I am thinking we should also print a list of users that we insert into the database at the start  of the program. The login utilizes check_credentials, so I removed it from the constructor.

### CODE REVIEW

**Review by alexaoh — CHANGES_REQUESTED** [review]
Looks great! I will make the UI_ctrl-class as discussed and you may continue from there <44

**Review by alexaoh — CHANGES_REQUESTED** [review]
Looks great! I think we are closing in on finishing. I will push a new commit with some new changes that are made. In part, I changed from camelCase to snake_case and removed the inserting from Python (it is via the txt-file, as discussed)

Things to look at:
1. Comment about a user choosing a Course. Decide what you want to do here. The Course-table can be filled via the txt.file. 

Possible problems found: 
1. It is possible to insert empty values (querying my database shows that the fields are empty, not NULL, have a look at the pic below) when making a Post. This should not be possible. 
image

2. When taking inputs in feature_two(), it is not checked whether or not the datatype of the input is correct. I will try to fix this (in my next commit), but please check that it works as expected on your end as well.

**Review by alexaoh — APPROVED** [review]
You have fixed all my complaints! Looks great!

**Review by alexaoh — APPROVED** [review]
Looks great! Approved once again ;) If you don't think we should wait for @molderskog 's data, please merge ;))))

**Review by molderskog — APPROVED** [review]
Looks good and works like a charm!

**Pull request merged**
